export default [
	{
		'characterID': 1,
		'characterName': 'JSTEW',
		'raceID': 1,
		'klassID': 12,
		'level': 3,
		'alignment': null,
		'hp': 0,
		'maxHP': 10,
		'currencyCP': 0,
		'currencySP': 0,
		'currencyEP': 0,
		'currencyGP': 0,
		'currencyPP': 0,
		'strength': 6,
		'dexterity': 1,
		'constitution': 1,
		'intelligence': 1,
		'wisdom': 1,
		'charism': 1,
		'characterDesc': null,
		'backstory': null,
		'height': '',
		'weight': 0,
		'age': 0,
		'skinDesc': '',
		'hairDesc': '',
		'avatarURL': null,
		'isNPC': 0,
		'ac': 15,
		'klassName': 'Wizard',
		'raceName': 'Dwarf',
		'raceSpeed': 30,
		'spells': [],
		'proficiencies': [],
		'equipment': [],
		'klassFeatures': [
			{
				'featID': 400,
				'featName': 'Spellcasting',
				'featDesc': 'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.',
				'featLevel': 1,
			},
			{
				'featID': 401,
				'featName': 'Arcane Recovery',
				'featDesc': 'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.,For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.',
				'featLevel': 1,
			}, { 'featID': 402, 'featName': 'Arcane Tradition', 'featDesc': 'When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, or Transmutation, all detailed at the end of the class description.,Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.', 'featLevel': 2 }, { 'featID': 403, 'featName': 'Evocation Savant', 'featDesc': 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.', 'featLevel': 2 }, { 'featID': 404, 'featName': 'Sculpt Spells', 'featDesc': 'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can choose a number of them equal to 1 + the spell’s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.', 'featLevel': 2 },
		],
	},
	{
		'characterID': 2,
		'characterName': 'JSTEW',
		'raceID': 1,
		'klassID': 12,
		'level': 3,
		'alignment': null,
		'hp': 0,
		'maxHP': 10,
		'currencyCP': 0,
		'currencySP': 0,
		'currencyEP': 0,
		'currencyGP': 0,
		'currencyPP': 0,
		'strength': 6,
		'dexterity': 1,
		'constitution': 1,
		'intelligence': 1,
		'wisdom': 1,
		'charism': 1,
		'characterDesc': null,
		'backstory': null,
		'height': '',
		'weight': 0,
		'age': 0,
		'skinDesc': '',
		'hairDesc': '',
		'avatarURL': null,
		'isNPC': 0,
		'ac': 15,
		'klassName': 'Wizard',
		'raceName': 'Dwarf',
		'raceSpeed': 30,
		'spells': [],
		'proficiencies': [],
		'equipment': [],
		'klassFeatures': [
			{
				'featID': 400,
				'featName': 'Spellcasting',
				'featDesc': 'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.',
				'featLevel': 1,
			},
			{
				'featID': 401,
				'featName': 'Arcane Recovery',
				'featDesc': 'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.,For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.',
				'featLevel': 1,
			}, { 'featID': 402, 'featName': 'Arcane Tradition', 'featDesc': 'When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, or Transmutation, all detailed at the end of the class description.,Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.', 'featLevel': 2 }, { 'featID': 403, 'featName': 'Evocation Savant', 'featDesc': 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.', 'featLevel': 2 }, { 'featID': 404, 'featName': 'Sculpt Spells', 'featDesc': 'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can choose a number of them equal to 1 + the spell’s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.', 'featLevel': 2 },
		],
	},
	{
		'characterID': 3,
		'characterName': 'JSTEW',
		'raceID': 1,
		'klassID': 12,
		'level': 3,
		'alignment': null,
		'hp': 0,
		'maxHP': 10,
		'currencyCP': 0,
		'currencySP': 0,
		'currencyEP': 0,
		'currencyGP': 0,
		'currencyPP': 0,
		'strength': 6,
		'dexterity': 1,
		'constitution': 1,
		'intelligence': 1,
		'wisdom': 1,
		'charism': 1,
		'characterDesc': null,
		'backstory': null,
		'height': '',
		'weight': 0,
		'age': 0,
		'skinDesc': '',
		'hairDesc': '',
		'avatarURL': null,
		'isNPC': 0,
		'ac': 15,
		'klassName': 'Wizard',
		'raceName': 'Dwarf',
		'raceSpeed': 30,
		'spells': [],
		'proficiencies': [],
		'equipment': [],
		'klassFeatures': [
			{
				'featID': 400,
				'featName': 'Spellcasting',
				'featDesc': 'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.',
				'featLevel': 1,
			},
			{
				'featID': 401,
				'featName': 'Arcane Recovery',
				'featDesc': 'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.,For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.',
				'featLevel': 1,
			}, { 'featID': 402, 'featName': 'Arcane Tradition', 'featDesc': 'When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, or Transmutation, all detailed at the end of the class description.,Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.', 'featLevel': 2 }, { 'featID': 403, 'featName': 'Evocation Savant', 'featDesc': 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.', 'featLevel': 2 }, { 'featID': 404, 'featName': 'Sculpt Spells', 'featDesc': 'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can choose a number of them equal to 1 + the spell’s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.', 'featLevel': 2 },
		],
	},
	{
		'characterID': 4,
		'characterName': 'JSTEW',
		'raceID': 1,
		'klassID': 12,
		'level': 3,
		'alignment': null,
		'hp': 0,
		'maxHP': 10,
		'currencyCP': 0,
		'currencySP': 0,
		'currencyEP': 0,
		'currencyGP': 0,
		'currencyPP': 0,
		'strength': 6,
		'dexterity': 1,
		'constitution': 1,
		'intelligence': 1,
		'wisdom': 1,
		'charism': 1,
		'characterDesc': null,
		'backstory': null,
		'height': '',
		'weight': 0,
		'age': 0,
		'skinDesc': '',
		'hairDesc': '',
		'avatarURL': null,
		'isNPC': 1,
		'ac': 15,
		'klassName': 'Wizard',
		'raceName': 'Dwarf',
		'raceSpeed': 30,
		'spells': [],
		'proficiencies': [],
		'equipment': [],
		'klassFeatures': [
			{
				'featID': 400,
				'featName': 'Spellcasting',
				'featDesc': 'As a student of arcane magic, you have a spellbook containing spells that show the first glimmerings of your true power.',
				'featLevel': 1,
			},
			{
				'featID': 401,
				'featName': 'Arcane Recovery',
				'featDesc': 'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can choose expended spell slots to recover. The spell slots can have a combined level that is equal to or less than half your wizard level (rounded up), and none of the slots can be 6th level or higher.,For example, if you’re a 4th-level wizard, you can recover up to two levels worth of spell slots. You can recover either a 2nd-level spell slot or two 1st-level spell slots.',
				'featLevel': 1,
			}, { 'featID': 402, 'featName': 'Arcane Tradition', 'featDesc': 'When you reach 2nd level, you choose an arcane tradition, shaping your practice of magic through one of eight schools: Abjuration, Conjuration, Divination, Enchantment, Evocation, Illusion, Necromancy, or Transmutation, all detailed at the end of the class description.,Your choice grants you features at 2nd level and again at 6th, 10th, and 14th level.', 'featLevel': 2 }, { 'featID': 403, 'featName': 'Evocation Savant', 'featDesc': 'Beginning when you select this school at 2nd level, the gold and time you must spend to copy an evocation spell into your spellbook is halved.', 'featLevel': 2 }, { 'featID': 404, 'featName': 'Sculpt Spells', 'featDesc': 'Beginning at 2nd level, you can create pockets of relative safety within the effects of your evocation spells. When you cast an evocation spell that affects other creatures that you can see, you can choose a number of them equal to 1 + the spell’s level. The chosen creatures automatically succeed on their saving throws against the spell, and they take no damage if they would normally take half damage on a successful save.', 'featLevel': 2 },
		],
	},
];